services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn car_rental_service.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: car_rental_service.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
